#version: "3"
#
#volumes:
#  dbdata:
#
#services:
#  psqldb:
#    image:
#      postgres:alpine3.18
#    environment:
#      - POSTGRES_DB=fit_world
#    env_file:
#      - ./env/postgres.env
#    volumes:
#      - dbdata:/var/lib/postgresql/data

services:
  backend:
    depends_on:
      - db
    build: . # swagger_rest # backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=fit_world
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: unless-stopped
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=fit_world
      #      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_PASSWORD=penon.veserti
    expose:
      - 5432
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:
